name: docker build and deploy

on:
  push:
    branches:
      - master
    ignore-paths:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: build & push worker docker image
      run: |
        DOCKER_TAG=$(echo $GITHUB_SHA | head -c7)
        echo $DOCKER_TAG > GITREF
        docker build . --file Dockerfile --tag ghcr.io/v4lli/prioritle:$DOCKER_TAG --tag ghcr.io/v4lli/prioritle:latest
        docker push ghcr.io/v4lli/prioritle:$DOCKER_TAG
        docker push ghcr.io/v4lli/prioritle:latest
